// No import needed for Department, as it is declared globally in the .d.ts file

export const departmentsData: Department[] = [
  {
    id: 'crown-bridge',
    name: 'Crown & Bridge',
    description: 'Specializing in crowns, bridges, and fixed prosthetics',
    totalCases: 45,
    pendingCases: 12,
    completedToday: 8,
    waitingInward: [
      {
        id: 'WAIT001',
        caseNumber: 'ADE-2025-045',
        doctorName: 'Dr. Amit Sharma',
        clinicName: 'City Dental Hub',
        patientName: 'Priya Reddy',
        caseType: 'Crown',
        priority: 'medium',
        expectedDate: '2025-06-09',
        notes: 'Case ready for inward processing',
        logs: [
          {
            id: 'L1',
            timestamp: '2025-06-04 10:00',
            action: 'Case Received',
            user: 'Dr. Amit Sharma',
            details: 'Initial case submission',
          },
        ],
        digitalFiles: [
          {
            id: 'F1',
            name: 'impression.stl',
            type: 'STL',
            size: '2.4 MB',
            uploadedBy: 'Dr. Amit Sharma',
            uploadedAt: '2025-06-04',
            url: '#',
          },
        ],
        products: [],
        accessories: [],
      },
      {
        id: 'WAIT002',
        caseNumber: 'ADE-2025-046',
        doctorName: 'Dr. Neha Gupta',
        clinicName: 'Smile Studio',
        patientName: 'Raj Patel',
        caseType: 'Bridge',
        priority: 'high',
        expectedDate: '2025-06-08',
        notes: 'Urgent case - patient traveling',
        logs: [
          {
            id: 'L2',
            timestamp: '2025-06-04 11:00',
            action: 'Case Received',
            user: 'Dr. Neha Gupta',
            details: 'Urgent case submission',
          },
        ],
        digitalFiles: [
          {
            id: 'F2',
            name: 'scan.dcm',
            type: 'DICOM',
            size: '5.1 MB',
            uploadedBy: 'Dr. Neha Gupta',
            uploadedAt: '2025-06-04',
            url: '#',
          },
        ],
        products: [],
        accessories: [],
      },
      // More waitingInward cases...
      {
        id: 'WAIT003',
        caseNumber: 'ADE-2025-049',
        doctorName: 'Dr. Sameer Joshi',
        clinicName: 'Dental Artistry',
        patientName: 'Meena Kumari',
        caseType: 'Crown',
        priority: 'low',
        expectedDate: '2025-06-12',
        notes: 'Patient prefers metal-free',
        logs: [],
        digitalFiles: [],
        products: [],
        accessories: [],
      },
    ],
    inwardPending: [
      {
        id: 'IN001',
        caseNumber: 'ADE-2025-040',
        doctorName: 'Dr. Kavita Singh',
        clinicName: 'Elite Dental Care',
        patientName: 'Rohit Kumar',
        caseType: 'Crown',
        priority: 'high',
        receivedDate: '2025-06-04',
        dueDate: '2025-06-10',
        notes: 'Patient requires ceramic crown',
        logs: [
          {
            id: 'L3',
            timestamp: '2025-06-04 09:00',
            action: 'Made Inward',
            user: 'Admin',
            details: 'Case processed for assignment',
          },
        ],
        digitalFiles: [
          {
            id: 'F3',
            name: 'xray.jpg',
            type: 'Image',
            size: '1.2 MB',
            uploadedBy: 'Dr. Kavita Singh',
            uploadedAt: '2025-06-04',
            url: '#',
          },
        ],
        products: [],
        accessories: [
          {
            id: 'A1',
            name: 'Impression Material',
            quantity: 1,
            providedBy: 'doctor',
            notes: 'High quality silicone',
          },
        ],
      },
      // More inwardPending cases...
      {
        id: 'IN002',
        caseNumber: 'ADE-2025-041',
        doctorName: 'Dr. Suresh Rao',
        clinicName: 'Smile Avenue',
        patientName: 'Amitabh Bachchan',
        caseType: 'Bridge',
        priority: 'medium',
        receivedDate: '2025-06-05',
        dueDate: '2025-06-12',
        notes: '',
        logs: [],
        digitalFiles: [],
        products: [],
        accessories: [],
      },
    ],
    outwardPending: [
      {
        id: 'OUT001',
        caseNumber: 'ADE-2025-032',
        doctorName: 'Dr. Rajesh Kumar',
        clinicName: 'Smile Dental',
        patientName: 'Anita Sharma',
        caseType: 'Crown',
        priority: 'medium',
        completedDate: '2025-06-03',
        technicianName: 'Riya Patel',
        readyForOutward: true,
        logs: [
          {
            id: 'L4',
            timestamp: '2025-06-03 16:00',
            action: 'Work Completed',
            user: 'Riya Patel',
            details: 'Crown fabrication completed',
          },
        ],
        digitalFiles: [
          {
            id: 'F4',
            name: 'final_crown.stl',
            type: 'STL',
            size: '3.1 MB',
            uploadedBy: 'Riya Patel',
            uploadedAt: '2025-06-03',
            url: '#',
          },
        ],
        products: [
          {
            id: 'P1',
            name: 'Zirconia Crown',
            quantity: 1,
            cost: 150,
            addedBy: 'Riya Patel',
            addedAt: '2025-06-03',
          },
        ],
        accessories: [],
      },
      // More outwardPending cases...
    ],
    technicians: [
      {
        id: 'T001',
        name: 'Riya Patel',
        email: 'riya.patel@adelabs.com',
        department: 'Crown & Bridge',
        specialization: 'Ceramic Crowns',
        experience: '5 years',
        status: 'busy',
        currentCases: 3,
        assignments: [
          {
            id: 'A001',
            caseId: 'ADE-2025-034',
            caseNumber: 'ADE-2025-034',
            doctorName: 'Dr. Pooja Verma',
            clinicName: 'Smile Care Dental',
            patientName: 'Rahul Sharma',
            caseType: 'Crown',
            priority: 'high',
            status: 'in_progress',
            assignedDate: '2025-06-01',
            dueDate: '2025-06-06',
            estimatedCompletion: '2025-06-05',
            notes: 'Patient prefers ceramic material',
            technicianId: 'T001',
            technicianName: 'Riya Patel',
            logs: [],
            digitalFiles: [],
            products: [],
            accessories: [],
          },
        ],
      },
      {
        id: 'T002',
        name: 'Anita Gupta',
        email: 'anita.gupta@adelabs.com',
        department: 'Crown & Bridge',
        specialization: 'Zirconia Crowns',
        experience: '7 years',
        status: 'available',
        currentCases: 1,
        assignments: [],
      },
      // More technicians...
    ],
  },
  // More departments (orthodontics, dentures, etc.) with more data...
]; 