import { TaskItem } from "./types";

export const mockTasks: TaskItem[] = [
  {
    id: "ORD-1001",
    caseType: "Crown - Zirconia",
    priority: "high",
    dueDate: "2025-08-20",
    status: "Assigned",
    tooth: "#14",
    notes: "Shade A2",
  },
  {
    id: "ORD-1002",
    caseType: "Bridge - 3 Unit",
    priority: "medium",
    dueDate: "2025-08-18",
    status: "Accepted",
    tooth: "#11-13",
    notes: "Check margins",
  },
  {
    id: "ORD-1003",
    caseType: "Veneer",
    priority: "urgent",
    dueDate: "2025-08-10",
    status: "In Progress",
    tooth: "#8",
    notes: "Rush case",
  },
  {
    id: "ORD-1004",
    caseType: "Implant Crown",
    priority: "high",
    dueDate: "2025-08-25",
    status: "Completed",
    tooth: "#30",
    notes: "Screw retained",
  },
  {
    id: "ORD-1005",
    caseType: "Night Guard",
    priority: "low",
    dueDate: "2025-08-28",
    status: "Assigned",
    notes: "Soft, 2mm",
  },
  {
    id: "ORD-1006",
    caseType: "Crown - E.max",
    priority: "medium",
    dueDate: "2025-08-14",
    status: "Accepted",
    tooth: "#19",
    notes: "Try-in before glaze",
  },
  {
    id: "ORD-1007",
    caseType: "Partial Denture",
    priority: "high",
    dueDate: "2025-08-22",
    status: "In Progress",
    notes: "Metal framework",
  },
  {
    id: "ORD-1008",
    caseType: "Retainer",
    priority: "low",
    dueDate: "2025-08-30",
    status: "Completed",
    notes: "Clear",
  },
  {
    id: "ORD-1009",
    caseType: "Crown - PFM",
    priority: "medium",
    dueDate: "2025-08-19",
    status: "Assigned",
    tooth: "#3",
    notes: "Occlusal clearance",
  },
  {
    id: "ORD-1010",
    caseType: "Onlay",
    priority: "high",
    dueDate: "2025-08-16",
    status: "Accepted",
    tooth: "#15",
    notes: "Stain characterization",
  },
  {
    id: "ORD-1011",
    caseType: "Bridge - 4 Unit",
    priority: "urgent",
    dueDate: "2025-08-12",
    status: "In Progress",
    notes: "Expedite milling",
  },
  {
    id: "ORD-1012",
    caseType: "Crown - Zirconia",
    priority: "medium",
    dueDate: "2025-08-27",
    status: "Completed",
    tooth: "#20",
    notes: "Polish only",
  },
];
